general:
  local_ip: 000.000.000.000
graylog:
    host: host
    use: false
steam:
  api_key: XXXXXXXXXXXX
mongodb:
  host: mongodb://IP:27017/
  db: db_name
  db_dev: db_name_dev
  collection: collection_name
api:
  allowed_tokens:
    - token1
    - token2
    - token3
test_case:
  user_cookie: ThisIsAUserCookieString
webhooks:
  discord:
    url_list:
      - https://discord.com/api/webhooks/A
      - https://discord.com/api/webhooks/A
    use_discord: false
    moderation_urls:
      - https://discord.com/api/webhooks/A
      - https://discord.com/api/webhooks/A